# 1. Create a 3x3x3 array with random values 

In [ ]:
import numpy as np
data=np.random.rand(3,3,3)
print(data)

[[[0.78327286 0.13058912 0.18646355]
  [0.01534546 0.48266869 0.08725464]
  [0.91060997 0.49887104 0.24464883]]

 [[0.66304391 0.87361809 0.94784171]
  [0.31556177 0.80869442 0.45088338]
  [0.57563024 0.18924431 0.49394344]]

 [[0.02638019 0.81419434 0.96876785]
  [0.25886961 0.76459972 0.94464885]
  [0.18124452 0.66720107 0.93464897]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
import numpy as np
data=np.zeros((5,5))
print(data)
i=1
while i>0 and i<5:
    data[i][i-1]=i
    i=i+1
print("final matrix:\n",data)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
final matrix:
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
i=0
j=0
import numpy as np
data=np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i+j)%2!=0:
            data[i][j]=1
print(data)
            


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [ ]:
import numpy as np
data= np.random.rand(5,5)
print("Before normalization:")
print(data)
max = data.max()
min = data.min()
data = (data - min)/(max - min)
print("After normalization:")
print(data)

Before normalization:
[[0.1298128  0.94262562 0.92875351 0.30657355 0.92837547]
 [0.69144326 0.49817619 0.53225612 0.83314574 0.21032885]
 [0.72648024 0.83408152 0.09165915 0.3073521  0.65768341]
 [0.09993611 0.18049493 0.57997649 0.9622908  0.06176945]
 [0.95052546 0.10600708 0.25778557 0.99360289 0.65572562]]
After normalization:
[[0.07302094 0.94529358 0.93040667 0.26271229 0.93000098]
 [0.67573643 0.46833127 0.50490425 0.8278049  0.15942699]
 [0.71333648 0.82880913 0.03207622 0.26354779 0.63950695]
 [0.04095867 0.12741062 0.55611551 0.96639733 0.        ]
 [0.95377131 0.04747375 0.21035531 1.         0.63740594]]


# 5.  How to find common values between two arrays?

In [ ]:
import numpy as np
data=np.array([[1,2,3],[4,5,6]])
data1=np.array([[1,8,9],[2,11,4]])
data2=np.intersect1d(data,data1)
print("1st array:",data)
print("2nd array:",data1)
print("common elements:",data2)

1st array: [[1 2 3]
 [4 5 6]]
2nd array: [[ 1  8  9]
 [ 2 11  4]]
common elements: [1 2 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [ ]:
import numpy as np
today=np.datetime64('today','D')
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("yesterday:",yesterday)
print("today:",today)
print("tomorrow:",tomorrow)

yesterday: 2020-07-24
today: 2020-07-25
tomorrow: 2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [ ]:
import numpy as np
A=np.random.rand(3,4)
B=np.random.rand(3,4)
print(A)
print(B)
compare=A==B
ans=compare.all()
print(ans)

[[0.86359509 0.81188304 0.44279588 0.09100522]
 [0.26737679 0.00678421 0.37559469 0.81983804]
 [0.41884213 0.28570817 0.6155483  0.51636014]]
[[0.08197378 0.01414487 0.81987955 0.42642688]
 [0.03066143 0.49034693 0.9905662  0.77558331]
 [0.54070176 0.78626604 0.21910142 0.91951015]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
import numpy as np
data=np.random.rand(10)
print(data)
data[np.where(data == np.amax(data))]=0
print(data)


[0.88899714 0.48937731 0.40436942 0.52642676 0.30962541 0.44971645
 0.2271     0.7960998  0.89591571 0.18589232]
[0.88899714 0.48937731 0.40436942 0.52642676 0.30962541 0.44971645
 0.2271     0.7960998  0.         0.18589232]


# 9. How to print all the values of an array?

In [5]:
import numpy as np
import sys
data=np.random.rand(1000)
np.set_printoptions(threshold=sys.maxsize)
print(data)

[0.68189679 0.53995947 0.36014277 0.8293927  0.17109424 0.4821486
 0.86202497 0.82667062 0.93040771 0.00600531 0.43844115 0.2462791
 0.00867841 0.70193443 0.19326012 0.77068336 0.74102811 0.40341412
 0.4601821  0.88906262 0.86114835 0.25818905 0.74224623 0.46285615
 0.72268316 0.53934732 0.66621903 0.8495988  0.87196174 0.69180564
 0.08855771 0.17462006 0.98874799 0.11097892 0.63498171 0.0385689
 0.51795338 0.74706003 0.41422476 0.22157577 0.35417889 0.97527228
 0.57066522 0.92863665 0.88877838 0.83707706 0.94956299 0.73517694
 0.01017702 0.02586983 0.89489979 0.75421712 0.01481982 0.21080132
 0.98007995 0.46370555 0.14758035 0.87018891 0.50598922 0.24248397
 0.00156543 0.8205034  0.9981469  0.05694401 0.50114776 0.89912694
 0.77519013 0.15922101 0.45998106 0.82929871 0.34374483 0.76748376
 0.57842966 0.57035211 0.68431777 0.6826275  0.75089909 0.2059305
 0.50793199 0.79116804 0.5454479  0.40816762 0.98264533 0.67422188
 0.90087674 0.0283325  0.50923726 0.55925853 0.72923682 0.48169659

# 10.Subtract the mean of each row of a matrix

In [13]:
import numpy as np
print("Original matrix:\n")
data = np.random.rand(3,3)
print(data)
data1= data - data.mean(axis=1, keepdims=True)
print("New matrix:\n",data1)


Original matrix:

[[0.66617048 0.60838092 0.05104724]
 [0.75576385 0.74176156 0.86001819]
 [0.5225456  0.88758134 0.2408312 ]]
New matrix:
 [[ 0.22430427  0.16651471 -0.39081897]
 [-0.03008401 -0.04408631  0.07417032]
 [-0.02777378  0.33726196 -0.30948818]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [30]:
import numpy as np
data=np.array([11,22,33,44,55])
print("1st vector:",data)
data1=np.array([0,1,3,1,0,4,2,1,1])
print("Before removing dupliccates from 2nd vector",data1)
l=data1.tolist()
l = list(dict.fromkeys(l))
data1=np.array(l)

print("2nd vector:",data1)
if len(data)>=len(data1):
    data2=np.zeros_like(data)
    data2[data1]=1
    print("Output:\n",data+data2)
else:
    print("Enter compatible input")


1st vector: [11 22 33 44 55]
Before removing dupliccates from 2nd vector [0 1 3 1 0 4 2 1 1]
2nd vector: [0 1 3 4 2]
Output:
 [12 23 34 45 56]


# 12.How to get the diagonal of a dot product?

In [37]:
import numpy as np
a=np.arange(25).reshape(5,5)
print("array1:\n",a)
b=np.arange(25).reshape(5,5)
print("array2:\n",b)
c=a.dot(b)
print("dot product:\n",c)
d=c.diagonal()
print("diagonal elemts of dot product:\n",d)

array1:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
array2:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
dot product:
 [[ 150  160  170  180  190]
 [ 400  435  470  505  540]
 [ 650  710  770  830  890]
 [ 900  985 1070 1155 1240]
 [1150 1260 1370 1480 1590]]
diagonal elemts of dot product:
 [ 150  435  770 1155 1590]


# 13.How to find the most frequent value in an array?

In [40]:
import numpy as np
import scipy.stats
a=np.array([[1,2,3,4],[1,4,5,4],[1,1,1,1]])
b=scipy.stats.mode(a,axis=None)
print(b)

ModeResult(mode=array([1]), count=array([6]))


# 14.How to get the n largest values of an array

In [41]:
import numpy as np
data= np.random.rand(5,5)
print(data)
max = data.max()
print("maximum value:",max)

[[0.58989969 0.88552142 0.02282784 0.59372359 0.82679741]
 [0.59540335 0.96000666 0.11258683 0.93503159 0.11144505]
 [0.67815671 0.04093011 0.5324544  0.1046256  0.60152755]
 [0.84363858 0.69145232 0.70586451 0.94043535 0.79050846]
 [0.81964387 0.90807533 0.19200828 0.05598587 0.88050353]]
maximum value: 0.9600066554549955


# 15.How to create a record array from a regular array?

In [45]:
import numpy as np
a1=np.array([1,2,3,4,5])
a2=np.array(["sector1","sector2","sectror3-dwarka","sectror3-surendranagar","kashmiri gate"])
a3=np.array([12.20,15,20,40,70])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result[4])
print(result)

(1, 'sector1', 12.2)
(2, 'sector2', 15.)
(3, 'sectror3-dwarka', 20.)
(4, 'sectror3-surendranagar', 40.)
(5, 'kashmiri gate', 70.)
[(1, 'sector1', 12.2) (2, 'sector2', 15. ) (3, 'sectror3-dwarka', 20. )
 (4, 'sectror3-surendranagar', 40. ) (5, 'kashmiri gate', 70. )]
