In [1]:
import os
os.chdir(r"C:\Users\User\Desktop\AI-ML\Day 27\SVM")

In [2]:
import pandas as pd
dataset=pd.read_csv("train.csv")
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
le=preprocessing.LabelEncoder()
dataset['Sex']=le.fit_transform(dataset['Sex'])
dataset['Embarked']=le.fit_transform(dataset['Embarked'])

In [4]:
from sklearn import svm
import numpy as np

In [5]:
dataset=dataset.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)
columns=['Survived','Pclass', 'Sex', 'SibSp',
       'Parch', 'Embarked']
for column_name in columns:
    y=dataset[column_name]
    X=dataset.drop(column_name,axis=1)
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
    from sklearn.naive_bayes import*
    clf=svm.SVC(gamma=0.01,C=100)
    print(column_name)
    y_pred=clf.fit(X_train,y_train).predict(X_test)
    print(accuracy_score(y_test,y_pred,normalize=True))
    print(confusion_matrix(y_test,y_pred))

Survived
0.6853932584269663
[[80 25]
 [31 42]]
Pclass
0.9213483146067416
[[43  4  0]
 [ 3 28  4]
 [ 0  3 93]]
Sex
0.6853932584269663
[[37 26]
 [30 85]]
SibSp
0.797752808988764
[[110  14   0   0   0   0   0]
 [ 13  25   2   0   0   0   0]
 [  2   1   1   0   0   0   0]
 [  0   2   1   2   1   0   0]
 [  0   0   0   0   1   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]
Parch
0.7808988764044944
[[125   3   5   0   0   0]
 [ 13   8   1   0   0   1]
 [  7   7   6   0   0   0]
 [  0   0   1   0   0   0]
 [  1   0   0   0   0   0]
 [  0   0   0   0   0   0]]
Embarked
0.7584269662921348
[[ 11   2  17]
 [  0   5  11]
 [ 11   2 119]]
